// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaWGfsVBbdEYFEPhO7dJtwHapmw3L5_yk',
    appId: '1:879524914856:web:acc90e8e4459114d86049d',
    messagingSenderId: '879524914856',
    projectId: 'swdnearex',
    authDomain: 'swdnearex.firebaseapp.com',
    storageBucket: 'swdnearex.appspot.com',
    measurementId: 'G-ESDBNC0F25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQeUVD8o8yipWeHmNU-LCJSphiceU3Hg',
    appId: '1:879524914856:android:82d0b4b2dcb9ee7586049d',
    messagingSenderId: '879524914856',
    projectId: 'swdnearex',
    storageBucket: 'swdnearex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMytpf2bl0WHjAf1X9dnLbP-n8d7Cjb4I',
    appId: '1:879524914856:ios:e8fe128fd566bd3086049d',
    messagingSenderId: '879524914856',
    projectId: 'swdnearex',
    storageBucket: 'swdnearex.appspot.com',
    iosClientId: '879524914856-3lkh5co797l0vqh9v1q7dhv8tavs2a3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMytpf2bl0WHjAf1X9dnLbP-n8d7Cjb4I',
    appId: '1:879524914856:ios:209362a9f7ae021586049d',
    messagingSenderId: '879524914856',
    projectId: 'swdnearex',
    storageBucket: 'swdnearex.appspot.com',
    iosClientId: '879524914856-4t3bns1tjoloafau8dn2o2fqljlg1130.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearex.RunnerTests',
  );
}
